name: Aliucord

on:
  workflow_dispatch:
    inputs:
      task_name:
        description: Task to run
        type: choice
        options:
        - none
        - disassembleWithPatches
        - writePatches
        - testPatches
      checkout_aliucord:
        description: Checkout Aliucord
        type: boolean

jobs:
  aliucord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: ${{ inputs.checkout_aliucord && '.github/workflows/run-task.yml' || null }}

      - name: Checkout Aliucord
        if: ${{ inputs.checkout_aliucord }}
        run: |
          rm -rf .git && git init -b main
          git fetch https://github.com/Aliucord/Aliucord main
          git reset --hard FETCH_HEAD

      - name: Setup JDK 11
        if: ${{ inputs.task_name != 'none' }}
        uses: actions/setup-java@v5
        with:
          java-version: 11
          distribution: temurin

      - name: Setup Gradle
        if: ${{ inputs.task_name != 'none' }}
        uses: gradle/actions/setup-gradle@v5

      - name: Run Task
        if: ${{ inputs.task_name != 'none' }}
        run: |
          chmod +x gradlew && ./gradlew ":patches:${{ inputs.task_name }}"

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add -f -- .
          git commit -m "patches: ${{ inputs.task_name }}" || exit 0
          git push -f "https://${{ secrets.PAT }}@github.com/XyuzalKiller/Aliucord" main
