name: Extract Boot

on:
  workflow_dispatch:
    inputs:
      rom_link:
        description: ROM Link
        type: string
        required: true

jobs:
  extract-boot:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Boot
        run: |
          curl -L "${{ inputs.rom_link }}" | tar -xzf - --occurrence --no-anchored boot.img
          printf "[$(basename "${{ inputs.rom_link }}")](${{ inputs.rom_link }})" >> "$GITHUB_STEP_SUMMARY"

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: boot
          path: "**/boot.img"
