name: Generate Keystore

on:
  workflow_dispatch:
    inputs:
      keystore_name:
        description: The keystore name
        type: string
        default: release
        required: true
      keystore_password:
        description: The keystore password
        type: string
        default: androidreleasekey
        required: true
      keystore_alias:
        description: The keystore alias
        type: string
        default: androidrelease
        required: true
      keystore_cn:
        description: The keystore common name
        type: string
        default: Release
        required: true

jobs:
  generate-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin

      - name: Generate Keystore
        run: |
          keytool \
            -genkeypair \
            -keyalg RSA \
            -keystore "${{ inputs.keystore_name }}.keystore" \
            -keypass "${{ inputs.keystore_password }}" \
            -storepass "${{ inputs.keystore_password }}" \
            -alias "${{ inputs.keystore_alias }}" \
            -dname "CN=${{ inputs.keystore_cn }}" \
            -validity 9999

      - name: Upload Keystore
        uses: actions/upload-artifact@v5
        with:
          name: keystore
          path: "*.keystore"
