name: Keystore Gen

on:
  workflow_dispatch:
    inputs:
      name:
        description: The Keystore Name
        type: string
        default: release
        required: true
      password:
        description: The Keystore Password
        type: string
        default: androidreleasekey
        required: true
      alias:
        description: The Keystore Alias
        type: string
        default: androidrelease
        required: true
      common_name:
        description: The Keystore Common Name
        type: string
        default: Release
        required: true

jobs:
  keystore-gen:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Generate Keystore
        run: |
          keytool \
            -genkeypair \
            -keyalg RSA \
            -keystore "${{ inputs.name }}.keystore" \
            -keypass "${{ inputs.password }}" \
            -storepass "${{ inputs.password }}" \
            -alias "${{ inputs.alias }}" \
            -dname "CN=${{ inputs.common_name }}" \
            -validity 9999

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: keystore
          path: "*.keystore"