name: Remove Workflow Runs

on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
        description: Repository
        default: OWNER/REPO
        type: string
      workflow_name:
        required: true
        description: Workflow Name
        default: name.yml
        type: string

jobs:
  remove-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Workflow Runs
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh api --paginate --jq ".workflow_runs[].id" "/repos/${{ inputs.repository }}/actions/workflows/${{ inputs.workflow_name }}/runs" \
          | xargs -I {} gh run delete --repo "${{ inputs.repository }}" {}
